baseurl = "https://www.rasmuslarsson.se"
languageCode = "en-us"
theme = "hyde-x"
title = "Rasmus Larsson"
metaDataFormat = "yaml"
paginate = 10
uglyURLs = true

[author]
    name = "Rasmus Larsson"

[params]
    tagline = "Code, ramblings and other stuff."
    defaultDescription = "Code, ramblings and other stuff. The blog of Rasmus Larsson."
    defaultKeywords = "rasmus, larsson, programming, code, web, unix"

    truncate = false
    highlight = "solarized_dark"

    googleAuthorship = "RasmusLarsson1337" # Yeah, I know
    googleAnalytics = "UA-26257571-1"
