baseurl = "https://test.rasmuslarsson.se"
languageCode = "en-us"
theme = "hyde-x"
title = "Rasmus Larsson"

[author]
    name = "Rasmus Larsson"

[params]
    tagline = "Code, ramblings and other stuff."
    defaultDescription = "A description"
    defaultKeywords = "rasmus, larsson, programming, code, web, unix"

    truncate = false
    highlight = "solarized_dark"

    googleAuthorship = "RasmusLarsson1337" # Yeah, I know
    googleAnalytics = "UA-26257571-1"
