baseurl = "https://test.rasmuslarsson.se"
languageCode = "en-us"
theme = "hyde-x"
title = "Rasmus Larsson"

[author]
    name = "Rasmus Larsson"

[params]
    tagline = "Code, ramblings and other stuff."
